// export const GAME_INICIATE_TIMER = "GAME_INICIATE_TIMER";
// export const GAME_ADD_VICTORY = "GAME_ADD_VICTORY";
// export const GAME_RESUME = "GAME_RESUME";
// export const GAME_PAUSE = "GAME_PAUSE";

export const LOCATIONS_RESET = "LOCATIONS_RESET";
export const LOCATIONS_ADD = "LOCATIONS_ADD";

// export const BOARD_RESET = "BOARD_RESET";
// export const BOARD_SET_TILES = "BOARD_SET_TILES";
// export const BOARD_SELECT_TILE = "BOARD_SELECT_TILE";
// export const BOARD_CLEAR_SELECTIONS = "BOARD_CLEAR_SELECTIONS";
// export const BOARD_ADD_DISCOVERED = "BOARD_ADD_DISCOVERED";

